// Generated by gencpp from file beginner_tutorials/Scan_range.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SCAN_RANGE_H
#define BEGINNER_TUTORIALS_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Scan_range_
{
  typedef Scan_range_<ContainerAllocator> Type;

  Scan_range_()
    : maximum(0.0)
    , minimum(0.0)  {
    }
  Scan_range_(const ContainerAllocator& _alloc)
    : maximum(0.0)
    , minimum(0.0)  {
  (void)_alloc;
    }



   typedef double _maximum_type;
  _maximum_type maximum;

   typedef double _minimum_type;
  _minimum_type minimum;





  typedef boost::shared_ptr< ::beginner_tutorials::Scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct Scan_range_

typedef ::beginner_tutorials::Scan_range_<std::allocator<void> > Scan_range;

typedef boost::shared_ptr< ::beginner_tutorials::Scan_range > Scan_rangePtr;
typedef boost::shared_ptr< ::beginner_tutorials::Scan_range const> Scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Scan_range_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Scan_range_<ContainerAllocator2> & rhs)
{
  return lhs.maximum == rhs.maximum &&
    lhs.minimum == rhs.minimum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Scan_range_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Scan_range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Scan_range_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "794426e8c6a60ff752d8c666c7346466";
  }

  static const char* value(const ::beginner_tutorials::Scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x794426e8c6a60ff7ULL;
  static const uint64_t static_value2 = 0x52d8c666c7346466ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Scan_range";
  }

  static const char* value(const ::beginner_tutorials::Scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 maximum\n"
"float64 minimum\n"
;
  }

  static const char* value(const ::beginner_tutorials::Scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.maximum);
      stream.next(m.minimum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Scan_range_<ContainerAllocator>& v)
  {
    s << indent << "maximum: ";
    Printer<double>::stream(s, indent + "  ", v.maximum);
    s << indent << "minimum: ";
    Printer<double>::stream(s, indent + "  ", v.minimum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SCAN_RANGE_H
